# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pengwang/workspace/github/drpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pengwang/workspace/github/drpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengwang/workspace/github/drpc/CMakeFiles /home/pengwang/workspace/github/drpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengwang/workspace/github/drpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drpc

# Build rule for target.
drpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drpc
.PHONY : drpc

# fast build rule for target.
drpc/fast:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/build
.PHONY : drpc/fast

rpc.pb.o: rpc.pb.cc.o

.PHONY : rpc.pb.o

# target to build an object file
rpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/rpc.pb.cc.o
.PHONY : rpc.pb.cc.o

rpc.pb.i: rpc.pb.cc.i

.PHONY : rpc.pb.i

# target to preprocess a source file
rpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/rpc.pb.cc.i
.PHONY : rpc.pb.cc.i

rpc.pb.s: rpc.pb.cc.s

.PHONY : rpc.pb.s

# target to generate assembly for a file
rpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/rpc.pb.cc.s
.PHONY : rpc.pb.cc.s

service.pb.o: service.pb.cc.o

.PHONY : service.pb.o

# target to build an object file
service.pb.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/service.pb.cc.o
.PHONY : service.pb.cc.o

service.pb.i: service.pb.cc.i

.PHONY : service.pb.i

# target to preprocess a source file
service.pb.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/service.pb.cc.i
.PHONY : service.pb.cc.i

service.pb.s: service.pb.cc.s

.PHONY : service.pb.s

# target to generate assembly for a file
service.pb.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/service.pb.cc.s
.PHONY : service.pb.cc.s

src/async_socket.o: src/async_socket.cc.o

.PHONY : src/async_socket.o

# target to build an object file
src/async_socket.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/async_socket.cc.o
.PHONY : src/async_socket.cc.o

src/async_socket.i: src/async_socket.cc.i

.PHONY : src/async_socket.i

# target to preprocess a source file
src/async_socket.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/async_socket.cc.i
.PHONY : src/async_socket.cc.i

src/async_socket.s: src/async_socket.cc.s

.PHONY : src/async_socket.s

# target to generate assembly for a file
src/async_socket.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/async_socket.cc.s
.PHONY : src/async_socket.cc.s

src/async_watcher.o: src/async_watcher.cc.o

.PHONY : src/async_watcher.o

# target to build an object file
src/async_watcher.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/async_watcher.cc.o
.PHONY : src/async_watcher.cc.o

src/async_watcher.i: src/async_watcher.cc.i

.PHONY : src/async_watcher.i

# target to preprocess a source file
src/async_watcher.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/async_watcher.cc.i
.PHONY : src/async_watcher.cc.i

src/async_watcher.s: src/async_watcher.cc.s

.PHONY : src/async_watcher.s

# target to generate assembly for a file
src/async_watcher.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/async_watcher.cc.s
.PHONY : src/async_watcher.cc.s

src/channel.o: src/channel.cc.o

.PHONY : src/channel.o

# target to build an object file
src/channel.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/channel.cc.o
.PHONY : src/channel.cc.o

src/channel.i: src/channel.cc.i

.PHONY : src/channel.i

# target to preprocess a source file
src/channel.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/channel.cc.i
.PHONY : src/channel.cc.i

src/channel.s: src/channel.cc.s

.PHONY : src/channel.s

# target to generate assembly for a file
src/channel.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/channel.cc.s
.PHONY : src/channel.cc.s

src/event_loop.o: src/event_loop.cc.o

.PHONY : src/event_loop.o

# target to build an object file
src/event_loop.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/event_loop.cc.o
.PHONY : src/event_loop.cc.o

src/event_loop.i: src/event_loop.cc.i

.PHONY : src/event_loop.i

# target to preprocess a source file
src/event_loop.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/event_loop.cc.i
.PHONY : src/event_loop.cc.i

src/event_loop.s: src/event_loop.cc.s

.PHONY : src/event_loop.s

# target to generate assembly for a file
src/event_loop.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/event_loop.cc.s
.PHONY : src/event_loop.cc.s

src/event_loop_group.o: src/event_loop_group.cc.o

.PHONY : src/event_loop_group.o

# target to build an object file
src/event_loop_group.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/event_loop_group.cc.o
.PHONY : src/event_loop_group.cc.o

src/event_loop_group.i: src/event_loop_group.cc.i

.PHONY : src/event_loop_group.i

# target to preprocess a source file
src/event_loop_group.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/event_loop_group.cc.i
.PHONY : src/event_loop_group.cc.i

src/event_loop_group.s: src/event_loop_group.cc.s

.PHONY : src/event_loop_group.s

# target to generate assembly for a file
src/event_loop_group.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/event_loop_group.cc.s
.PHONY : src/event_loop_group.cc.s

src/ip_address.o: src/ip_address.cc.o

.PHONY : src/ip_address.o

# target to build an object file
src/ip_address.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/ip_address.cc.o
.PHONY : src/ip_address.cc.o

src/ip_address.i: src/ip_address.cc.i

.PHONY : src/ip_address.i

# target to preprocess a source file
src/ip_address.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/ip_address.cc.i
.PHONY : src/ip_address.cc.i

src/ip_address.s: src/ip_address.cc.s

.PHONY : src/ip_address.s

# target to generate assembly for a file
src/ip_address.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/ip_address.cc.s
.PHONY : src/ip_address.cc.s

src/json2pb/encode_decode.o: src/json2pb/encode_decode.cc.o

.PHONY : src/json2pb/encode_decode.o

# target to build an object file
src/json2pb/encode_decode.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/encode_decode.cc.o
.PHONY : src/json2pb/encode_decode.cc.o

src/json2pb/encode_decode.i: src/json2pb/encode_decode.cc.i

.PHONY : src/json2pb/encode_decode.i

# target to preprocess a source file
src/json2pb/encode_decode.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/encode_decode.cc.i
.PHONY : src/json2pb/encode_decode.cc.i

src/json2pb/encode_decode.s: src/json2pb/encode_decode.cc.s

.PHONY : src/json2pb/encode_decode.s

# target to generate assembly for a file
src/json2pb/encode_decode.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/encode_decode.cc.s
.PHONY : src/json2pb/encode_decode.cc.s

src/json2pb/json_to_pb.o: src/json2pb/json_to_pb.cc.o

.PHONY : src/json2pb/json_to_pb.o

# target to build an object file
src/json2pb/json_to_pb.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/json_to_pb.cc.o
.PHONY : src/json2pb/json_to_pb.cc.o

src/json2pb/json_to_pb.i: src/json2pb/json_to_pb.cc.i

.PHONY : src/json2pb/json_to_pb.i

# target to preprocess a source file
src/json2pb/json_to_pb.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/json_to_pb.cc.i
.PHONY : src/json2pb/json_to_pb.cc.i

src/json2pb/json_to_pb.s: src/json2pb/json_to_pb.cc.s

.PHONY : src/json2pb/json_to_pb.s

# target to generate assembly for a file
src/json2pb/json_to_pb.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/json_to_pb.cc.s
.PHONY : src/json2pb/json_to_pb.cc.s

src/json2pb/pb_to_json.o: src/json2pb/pb_to_json.cc.o

.PHONY : src/json2pb/pb_to_json.o

# target to build an object file
src/json2pb/pb_to_json.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/pb_to_json.cc.o
.PHONY : src/json2pb/pb_to_json.cc.o

src/json2pb/pb_to_json.i: src/json2pb/pb_to_json.cc.i

.PHONY : src/json2pb/pb_to_json.i

# target to preprocess a source file
src/json2pb/pb_to_json.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/pb_to_json.cc.i
.PHONY : src/json2pb/pb_to_json.cc.i

src/json2pb/pb_to_json.s: src/json2pb/pb_to_json.cc.s

.PHONY : src/json2pb/pb_to_json.s

# target to generate assembly for a file
src/json2pb/pb_to_json.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/pb_to_json.cc.s
.PHONY : src/json2pb/pb_to_json.cc.s

src/json2pb/protobuf_map.o: src/json2pb/protobuf_map.cc.o

.PHONY : src/json2pb/protobuf_map.o

# target to build an object file
src/json2pb/protobuf_map.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/protobuf_map.cc.o
.PHONY : src/json2pb/protobuf_map.cc.o

src/json2pb/protobuf_map.i: src/json2pb/protobuf_map.cc.i

.PHONY : src/json2pb/protobuf_map.i

# target to preprocess a source file
src/json2pb/protobuf_map.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/protobuf_map.cc.i
.PHONY : src/json2pb/protobuf_map.cc.i

src/json2pb/protobuf_map.s: src/json2pb/protobuf_map.cc.s

.PHONY : src/json2pb/protobuf_map.s

# target to generate assembly for a file
src/json2pb/protobuf_map.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/json2pb/protobuf_map.cc.s
.PHONY : src/json2pb/protobuf_map.cc.s

src/listener.o: src/listener.cc.o

.PHONY : src/listener.o

# target to build an object file
src/listener.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/listener.cc.o
.PHONY : src/listener.cc.o

src/listener.i: src/listener.cc.i

.PHONY : src/listener.i

# target to preprocess a source file
src/listener.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/listener.cc.i
.PHONY : src/listener.cc.i

src/listener.s: src/listener.cc.s

.PHONY : src/listener.s

# target to generate assembly for a file
src/listener.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/listener.cc.s
.PHONY : src/listener.cc.s

src/rpc_channel.o: src/rpc_channel.cc.o

.PHONY : src/rpc_channel.o

# target to build an object file
src/rpc_channel.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/rpc_channel.cc.o
.PHONY : src/rpc_channel.cc.o

src/rpc_channel.i: src/rpc_channel.cc.i

.PHONY : src/rpc_channel.i

# target to preprocess a source file
src/rpc_channel.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/rpc_channel.cc.i
.PHONY : src/rpc_channel.cc.i

src/rpc_channel.s: src/rpc_channel.cc.s

.PHONY : src/rpc_channel.s

# target to generate assembly for a file
src/rpc_channel.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/rpc_channel.cc.s
.PHONY : src/rpc_channel.cc.s

src/server.o: src/server.cc.o

.PHONY : src/server.o

# target to build an object file
src/server.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/server.cc.o
.PHONY : src/server.cc.o

src/server.i: src/server.cc.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/server.cc.i
.PHONY : src/server.cc.i

src/server.s: src/server.cc.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/server.cc.s
.PHONY : src/server.cc.s

src/socket.o: src/socket.cc.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/socket.cc.o
.PHONY : src/socket.cc.o

src/socket.i: src/socket.cc.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/socket.cc.i
.PHONY : src/socket.cc.i

src/socket.s: src/socket.cc.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/src/socket.cc.s
.PHONY : src/socket.cc.s

test/test_server.o: test/test_server.cc.o

.PHONY : test/test_server.o

# target to build an object file
test/test_server.cc.o:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/test/test_server.cc.o
.PHONY : test/test_server.cc.o

test/test_server.i: test/test_server.cc.i

.PHONY : test/test_server.i

# target to preprocess a source file
test/test_server.cc.i:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/test/test_server.cc.i
.PHONY : test/test_server.cc.i

test/test_server.s: test/test_server.cc.s

.PHONY : test/test_server.s

# target to generate assembly for a file
test/test_server.cc.s:
	$(MAKE) -f CMakeFiles/drpc.dir/build.make CMakeFiles/drpc.dir/test/test_server.cc.s
.PHONY : test/test_server.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... drpc"
	@echo "... edit_cache"
	@echo "... rpc.pb.o"
	@echo "... rpc.pb.i"
	@echo "... rpc.pb.s"
	@echo "... service.pb.o"
	@echo "... service.pb.i"
	@echo "... service.pb.s"
	@echo "... src/async_socket.o"
	@echo "... src/async_socket.i"
	@echo "... src/async_socket.s"
	@echo "... src/async_watcher.o"
	@echo "... src/async_watcher.i"
	@echo "... src/async_watcher.s"
	@echo "... src/channel.o"
	@echo "... src/channel.i"
	@echo "... src/channel.s"
	@echo "... src/event_loop.o"
	@echo "... src/event_loop.i"
	@echo "... src/event_loop.s"
	@echo "... src/event_loop_group.o"
	@echo "... src/event_loop_group.i"
	@echo "... src/event_loop_group.s"
	@echo "... src/ip_address.o"
	@echo "... src/ip_address.i"
	@echo "... src/ip_address.s"
	@echo "... src/json2pb/encode_decode.o"
	@echo "... src/json2pb/encode_decode.i"
	@echo "... src/json2pb/encode_decode.s"
	@echo "... src/json2pb/json_to_pb.o"
	@echo "... src/json2pb/json_to_pb.i"
	@echo "... src/json2pb/json_to_pb.s"
	@echo "... src/json2pb/pb_to_json.o"
	@echo "... src/json2pb/pb_to_json.i"
	@echo "... src/json2pb/pb_to_json.s"
	@echo "... src/json2pb/protobuf_map.o"
	@echo "... src/json2pb/protobuf_map.i"
	@echo "... src/json2pb/protobuf_map.s"
	@echo "... src/listener.o"
	@echo "... src/listener.i"
	@echo "... src/listener.s"
	@echo "... src/rpc_channel.o"
	@echo "... src/rpc_channel.i"
	@echo "... src/rpc_channel.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... test/test_server.o"
	@echo "... test/test_server.i"
	@echo "... test/test_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

